
- name: change network device's credentials
  hosts: network_device_group
  strategy: linear
  
  tasks:
    - name: prepare directory to store log files
      file:
        path: files/{{inventory_hostname}}
        state: directory
      when: not ("files/{{inventory_hostname}}" is exists)
      delegate_to: localhost
      tags:
        - always
        
    - name: include change credential's tasks
      include_tasks: tasks/change_device_credentials.yml
      when: (ansible_network_os is search("ios"))

- name: consolidate change's progress into report files
  hosts: localhost
  strategy: linear
  
  tasks:
    - name: consolidate change's progress into report files
      shell: "{{item}}"
      with_items:
        - echo "Hostname,Device IP,Status" > files/{{"%Y%m%d" | strftime}}.csv
        - cat files/*/*.status >> files/{{"%Y%m%d" | strftime}}.csv
      run_once: yes
      delegate_to: localhost
      tags:
        - consolidate_change_progress

- name: share report files to stackholders
  hosts: localhost
  strategy: linear

  tasks:
    - name: share report files to stackholders
      mail:
        host: smtp.gmail.com
        port: 587
        username: ayyappan.gnoc@gmail.com
        password: "{{mail_password}}"
        to:
          - ayyappan.gnoc@gmail.com
        subject: DevOps - Change Device Credentials
        body: |
          Hi Team,

          Please review attached reports and reach us immediately, in case of any issues.


          Regards,
          CPN Network Team, Channai
        attach: files/{{"%Y%m%d" | strftime}}.csv
      when: ("files/{{'%Y%m%d' | strftime}}.csv" is file)
      delegate_to: localhost
      tags:
        - share_change_progress
