
- name: copy change's progress into log files
  template:
    src: templates/device_login_failed.j2
    dest: files/{{inventory_hostname}}/{{inventory_hostname}}.status
  delegate_to: localhost
  tags:
    - change_device_credentials
    
- name: check device's login with exisiting credentials
  ios_command:
    commands: show clock
  when: (inventory_hostname is in(groups.network_switch_group))
  register: device_clock_results
  tags:
    - change_device_credentials
    
- name: copy change's progress into log files
  template:
    src: templates/device_login_checked.j2
    dest: files/{{inventory_hostname}}/{{inventory_hostname}}.status
  when: (device_clock_results is succeeded)
  delegate_to: localhost
  tags:
    - change_device_credentials

- name: change network device's credentials
  ios_command:
    commands:
      - configure terminal
      - enable secret {{expected_password}}
      - username adm1n secret {{expected_password}}
      - end
  when: (inventory_hostname is in(groups.network_switch_group))
  tags:
    - change_device_credentials
    
- name: copy device's configuration to startup file
  ios_config:
    save_when: always
  when: (inventory_hostname is in(groups.network_switch_group))
  tags:
    - change_device_credentials
    
- name: check device's login with expected credentials
  ios_command:
    commands: show clock
  when: (inventory_hostname is in(groups.network_switch_group))
  vars:
    ansible_password: "{{expected_password}}"
    ansible_become_password: "{{expected_password}}"
  register: device_clock_results
  tags:
    - change_device_credentials
    
- name: copy change's progress into log files
  template:
    src: templates/device_login_completed.j2
    dest: files/{{inventory_hostname}}/{{inventory_hostname}}.status
  when: (device_clock_results is succeeded)
  delegate_to: localhost
  tags:
    - change_device_credentials
